### ISSUE TITLE
Проблемы с цветом дальних дат после смены темы

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#100]
Работает на дальних датах. Нужно зайти в расписание, переместится на дальнюю дату (23 ноября, например) и нажать на неё, перейти в настройки и сменить тему. Вернуться в расписание и такая проблема. Воспроизводится на обеих темах.
![Screenshot_20201108-154152](https://user-images.githubusercontent.com/17129060/98465366-b4362800-21d9-11eb-8221-6eea261e7a2c.jpg)
![Screenshot_20201108-154125](https://user-images.githubusercontent.com/17129060/98465368-b5675500-21d9-11eb-960f-3fb73dc10561.jpg)

**Comment by tonykolomeytsev** [comment]
Мде) Похоже это из-за кэша RecycledViewPool. Нужно как-то чистить его при смене темы. 
Из-за того же кэша при смене темы не всегда карточки занятий перекрашиваются.

**Comment by tonykolomeytsev** [comment]
Бага починена в ветке `IS-0-refactoring`, сегодня исправления вольются в dev, через 2 дня в master.
Помог выпил `setRetainInstance = true` из фрагмента (`setRatainInstance`, кстати, deprecated начиная с `androidx.fragment:fragment:1.3.0` : https://developer.android.com/jetpack/androidx/releases/fragment#1.3.0 )
