### ISSUE TITLE
Предложение по дизайну

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#101]
1) Нижний разделитель меню на тёмной теме почти не заметен (сделать посветлее)
2) Уходя вверх пара обрезается, что выглядит не очень хорошо (тут могу предложить только либо градиент (как на втором скрине (убирает то неприятное чувство, когда видишь резкую обрезку)), либо добавить разделитель.
![Screenshot_20201108-153926](https://user-images.githubusercontent.com/17129060/98465449-29a1f880-21da-11eb-9e75-44b8b66e60bc.jpg)
![Снимок экрана 2020-11-08 155815](https://user-images.githubusercontent.com/17129060/98465624-40951a80-21db-11eb-8499-1bb0506bf8fc.png)

**Comment by tonykolomeytsev** [comment]
1. Я бы вообще убрал разделитель снизу. Да и это не совсем разделитель, это типа тень от bottomNav. По андроидовским гайдлайнам тень может быть только черного цвета.
2. Да, градиент выглядит приятнее. Вообще изначально хотел чтобы appBarLayout отбрасывал тень, если юзер хоть немного проскроллил. Так щас сделано в заметках и в настройках. Но в расписании такой маневр с appBarLayout, где есть pager, может стоить нам 51 год.

Подумаю по поводу градиента.

**Comment by tonykolomeytsev** [comment]
Градиент добавлен, заедет в версию 1.3.0
