### ISSUE TITLE
Даббл тач по паре открывает два окна с заметками

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#103]
Даббл тач по паре открывает два окна с заметками (в случае navcontroller вообще бы вылетал)). Решение - свой SafeClickListener с интервалом для срабатывания, или state machine, или просто булевый флаг

**Comment by tonykolomeytsev** [comment]
> в случае navcontroller вообще бы вылетал

Ахахаха поэтому я выпилил navController еще три месяца назад)

> SafeClickListener с интервалом для срабатывания

ClickListener с функцией Debounce норм идея, к через версию запилю наверное.

**Comment by tonykolomeytsev** [comment]
Добавил `setOnClickListenerWithDebounce` позволяющий блочить слишком частые клики.

```kotlin
fun View.setOnClickListenerWithDebounce(debounceDuration: Long, onClickListener: View.OnClickListener) {
    setOnClickListener(object : View.OnClickListener {
        private var lastClickMillis = System.currentTimeMillis()

        override fun onClick(v: View?) {
            val currentClickMillis = System.currentTimeMillis()
            if (currentClickMillis - lastClickMillis >= debounceDuration) {
                lastClickMillis = currentClickMillis
                onClickListener.onClick(v)
            }
        }
    })
}
```

**Comment by tonykolomeytsev** [comment]
Ну вот и все Issue от @tipapro закрыты)
