### ISSUE TITLE
Во вкладке с картой иконка выходит за границу

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#105]
Крайняя правая и левая иконки могут выходить за границу закругоённого
![Screenshot_20201109-093034](https://user-images.githubusercontent.com/17129060/98524367-2feeae00-2288-11eb-99af-6774abd383f0.jpg)

**Comment by tonykolomeytsev** [comment]
🤔

**Comment by tonykolomeytsev** [comment]
Сделал `clipToPadding=true` у recyclerView чтобы сами иконки не обрезались. Проблему выхода за пределы скругленных углов решил обойти с точки зрения дизайна:

![map_bottom_sheet_corners_demo](https://user-images.githubusercontent.com/18632470/108697658-3130a780-7514-11eb-9bba-256634ca71c4.gif)

Просто убираю скругления когда BottomSheet доходит до самого верха.
