### ISSUE TITLE
Нерабочие ссылки в embed-браузере

### ISSUE THREAD

**Issue by militaryCoder** [tonykolomeytsev/mpeiapp#144]
**Описание ошибки**
Во встроенном браузере под полями ввода лоигна и пароля есть ссылки "Получить учётную запись МЭИ, восстановить логин-пароль" и тому подобные. Суть в том, что при попытке перейти по ним происходит ровным счётом ничего.

**Как воспроизвести**
1. Идем в раздел профиля студента
2. Нажимаем на клавишу "Войти в БАРС"
3. Пытаемся перейти по какой-нибудь ссылке
4. Nothing happens!

**Ожидаемое поведение**
Ну, очевидно, при нажатии на ту же ссылку "Получить учётную запись МЭИ, восстановить логин-пароль" программа должна перекидывать либо в браузер на страницу восстановления, либо прямо в embed'е ее открывать.

**Смартфон (укажите всю информацию ниже):**
 - Устройство: Asus Zenfone Max Pro M2
 - ОС: Android 9
 - Версия приложения MpeiX for Android v1.8.0

**Comment by tonykolomeytsev** [comment]
Да, надо перекидывать в браузер, согласен. К обновлению поправлю

**Comment by tonykolomeytsev** [comment]
Исправление заехало в мастер, завтра будет релиз 1.9.0 и обновление в Google Play.
