### ISSUE TITLE
Отображение недельного расписания

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#21]
На вкладке timetable при переходе в ландшафтный режим отображать все 5 рабочих дней недели с парами. То есть показывать расписание сразу на всю неделю.

**Comment by tonykolomeytsev** [comment]
Я передумал

**Comment by mazuninky** [comment]
Однажды Эрнест Хемингуэй поспорил, что напишет самый короткий рассказ, способный растрогать любого...
