### ISSUE TITLE
Расписания заочников

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeiapp#71]
По обращению первокурсника-заочника обнаружилось две проблемы:

* Во-первых, номера групп у заочников вообще не влезают в ограничения поля `addscreen`.
* Во-вторых, группам заочников не заполняют расписания на сайте, а скидывают в личку в виде табличек xls.

Какой может быть выход?) Нужен парсер табличек или удобный интерфейс добавления расписаний в Firebase. Хз как это реализовать и кого нанимать супервайзером.

**Comment by mazuninky** [comment]
@tonykolomeytsev  Нужно в группе вк бота добавить, который будет принимать расписания. Тип хочешь расписание для своей группы - вноси xls. Ну и после ручками(полу-автоматически) уже заливать в бд и плашку в прилаге сделать для таких расписания "предоставлено сообществом/студентами"
