### ISSUE TITLE
Странное поведение дат в верхней панели

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#97]
Рандомное перемещение по датам приводит к неопределенному их поведению (пример на скриншотах)
![Screenshot_20201107-170053](https://user-images.githubusercontent.com/17129060/98443292-7a9ee780-211b-11eb-9b28-40edad9214f2.jpg)
![Screenshot_20201107-170139](https://user-images.githubusercontent.com/17129060/98443295-7d014180-211b-11eb-8378-0c3d7e7b84c7.jpg)
![Screenshot_20201107-170450](https://user-images.githubusercontent.com/17129060/98443296-7e326e80-211b-11eb-8fbe-4f8ffb53b71b.jpg)

**Comment by tonykolomeytsev** [comment]
Ага, прикольно. Имеется ввиду, баг возникает если быстро листать в разные стороны? Или еще каким-то образом?

**Comment by tipapro** [comment]
Вроде при медленном листании всё норм, а при быстром в одну сторону этот баг и появляется

**Comment by tonykolomeytsev** [comment]
Бага починена в ветке `IS-0-refactoring`, сегодня исправления вольются в dev, через 2 дня в master.
Проблема была в `WeeksScrollAdapter`, что в модуле `feature_schedule`. Адаптер дожидался данных о календаре, вместо того чтобы генерировать их самостоятельно, в итоге некоторые вызовы `onBindViewHolder `ничего не биндили и весь recyclerView с недельным календарем ломался.
