### ISSUE TITLE
После смены на тёмную тему, статус бар остаётся тёмным.

### ISSUE THREAD

**Issue by tipapro** [tonykolomeytsev/mpeiapp#98]
После смены на тёмную тему, статус бар остаётся тёмным. После перезапуска работает всё нормально.
![Screenshot_20201107-163812](https://user-images.githubusercontent.com/17129060/98443375-ee40f480-211b-11eb-9545-2a90dae68c71.jpg)

**Comment by tonykolomeytsev** [comment]
Знаю как это починить. Фикс войдет в новую версию
